# Generated by Django 3.0 on 2021-06-20 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_todolist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
