# Generated by Django 3.0 on 2021-06-21 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210621_0724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
