# Generated by Django 3.0 on 2021-06-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_todolist'),
        ('api', '0003_delete_user'),
    ]

    operations = [
    ]
